title: "Неумелый гекскроул"
description: "Блог о настольных ролевых играх в духе старой школы, oD&D, B/X, OSR"
baseurl: ""
url: "https://stuartzaq.github.io"
theme: minima
markdown: kramdown
kramdown:
  toc_levels: 1..3
highlighter: rouge
